### ISSUE TITLE
Why is this repo a thing

### ISSUE THREAD

**Issue by ghost** [TheSoliderror/H1-Server-Scripts#1]
Please make everyone a favor and keep your advanced scripts for yourself. Please.

**Comment by TheSoliderror** [comment]
> Please make everyone a favor and keep your advanced scripts for yourself. Please.

Sorry these are to advanced 😂

**Comment by ghost** [comment]
In all seriousness though, did you never even consider properly documenting your "releases"?
You're shipping unformated, hard to read Readme's in a .txt file while you ideally should use markdown.

Also, what would be somewhat cool/helpful is a command handler instead of on player say notifs everywhere, could turn out great if done properly :p

**Comment by mjkzy** [comment]
this could all be one script and configurable to be way better imo

**Comment by TheSoliderror** [comment]
Listen this shit was tossed together in like 10min, I just made them to get the job done. When I have time to fix it all I plan on redoing them all and making the ones that are all similar into one script and remove the ghetto bit script and it a real one to the game mode chooser so some modes either adds/removes them. This is all super shitty scripting but gets the job done for testing.
